spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_prod
    username: postgres_prod
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true