spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_dev
    username: postgres
    password: 123456_dev
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true